### ISSUE TITLE
Question on C Compatibility

### ISSUE THREAD

**Issue by thejmazz** [charto/nbind#14]
I understand there are some big differences between C and C++.

So I am not trying to say "please make this C compatible".

I'm just curious what the major differences are, if there are difficulties with C that don't exists for C++, etc.  As well, what you would recommend for achieving similar with C libs.

Thanks, this looks really cool, excited to try it out.

**Comment by jjrv** [comment]
You can always write a C++ wrapper calling the C code, and use nbind with that.

Since C doesn't have templates, there's no widely supported way to have the compiler generate new wrapper code for type conversion and output type information available at run-time. Instead, there would have to be a new tool that understands the C source code, reads types from function declarations and outputs additional C files with the generated wrappers.

Mapping idiomatic C to JavaScript classes would also be complicated, since it's common to reinvent new ways to do object-oriented programming, usually by using structs as classes and simulating methods by passing struct pointers to functions. Designing a nice JavaScript binding would in any case involve manual work annotating the purpose of such pointers, so the current approach of requiring a C++ wrapper shouldn't be worse in comparison.

Let me know if you have any ideas how C support should work, it would be interesting if a good solution comes up.

**Comment by thejmazz** [comment]
Cool thanks, I ask because I'm interested in using C libs like  [bwa](https://github.com/lh3/bwa) for [bionode](http://www.bionode.io/). asm won't have much use except for super small (probably synthetic) sequences for teaching bioinformatics on the browser, but could be cool for native from node side.

**Comment by jjrv** [comment]
Right now there's an ongoing effort to use [libui](https://github.com/andlabs/libui) (written in C) on Node.js using nbind and a C++ wrapper. Check out [libui-node](https://github.com/parro-it/libui-node) for a working example.

**Comment by jjrv** [comment]
The develop branch now has a readme section about using with plain C.
