### ISSUE TITLE
Design / performance 

### ISSUE THREAD

**Issue by KrishnaPG** [charto/nbind#21]
When using this mechanism - how are the parameters / data shared between the C++ and the Node?

For example, between .Net and C++, there is a whole marshalling (and unmarshalling) layer that sits in between, causing a big performance hit. (Try marshalling a big json/xml string between c++ and .net)

Similarly, any marshalling and unmarshalling happens here or is it a direct bind?

The reason I am asking is, to compare if it is worth using this technique or just host the c++ classes / methods directly in some custom http server. If this mechanism employs some kind of serde, then performance hiccups would be crucial.

**Comment by jjrv** [comment]
Numeric and boolean parameters are passed directly. Arrays / vectors require a single copy since their representation in the V8 JavaScript engine is different from normal stdlib data types. See [code](https://github.com/charto/nbind/blob/b261a466366479acdf6bf067535ac0014a69bb04/include/nbind/v8/BindingStd.h#L77-L113).

Strings are copied once (mainly by nan which abstracts away differences between Node.js versions) if you're happy with a `const char *` that you don't own (see [code](https://github.com/charto/nbind/blob/b261a466366479acdf6bf067535ac0014a69bb04/include/nbind/v8/BindingType.h#L161-L176) and [code](https://github.com/nodejs/nan/blob/62e7c84b62361f5f22a367504e741cdaf114edbe/nan.h#L894-L901)), or twice if you need `std::string` (see [code](https://github.com/charto/nbind/blob/b261a466366479acdf6bf067535ac0014a69bb04/include/nbind/v8/BindingStd.h#L119-L136
)).

Buffers are currently not supported but their situation will probably be the same as with strings. If you need buffer support, open an issue and I'll try to get them done sooner.

Nothing needs serializing to any temporary format, so there's just a single type conversion for native Node.js addons. If targeting asm.js there's an additional simple in-memory binary format, for example vectors are converted to a list of items with a length header (probably a similar format as stdlib stores internally, but a separate format guarantees JavaScript can read directly from the asm.js heap).

The closest to marshalling is what happens if you pass objects by value between the languages. As a stack-allocated object has nowhere to go directly, there's the option to define equivalent classes in both languages with and a `toJS` or `fromJS` method. Both receive a callback that takes parameters for calling the equivalent constructor in the other language. This is perfect for things like coordinate pairs or RGB values.

**Comment by KrishnaPG** [comment]
Thank you for the detailed info. It is very helpful.
