### ISSUE TITLE
Minor resolve issue

### ISSUE THREAD

**Issue by kenOfYugen** [charto/nbind#31]
Upon using `$ npm install charto/nbind#<branch>`, although the `main` field is specified in `node_modules/nbind/package.json` as `dist/nbind.js`, the module cannot be loaded with `require('nbind')`, since `dist` folder isn't included in the repo.

**Comment by jjrv** [comment]
Annoying that `npm` doesn't automatically run the `prepublish` script in that case... The `dist` directory shouldn't really be in version control, since it's just TypeScript compiler output. We only want the original source in Git, otherwise all changes would show up twice in commits. I think it's just necessary to run `npm install` in the `node_modules/nbind` after installing that way.

**Comment by kenOfYugen** [comment]
Yeah thought this was the case.

Calling the `prepublish` script requires `tslint` and `typescript`. So maybe they should be added as `devDependencies` in case they are not installed globally.

After adding them, `/src/em/em-api.ts` and `/src/em/emscripten.d.ts` are reported missing.

I am wondering if adding a `postinstall` script would work as trigger.
```json
"postinstall": "npm run prepublish"
```

**Comment by jjrv** [comment]
It seems the correct answer and how the TypeScript project handles this is by publishing nightly snapshot releases on NPM. It's usually not necessary for nbind though. I'll probably merge the `develop` branch to `master` and do a new release this week. The only missing thing to fix is automatically upcasting child to parent class instances on the Emscripten target. Then multiple inheritance should also be supported.

**Comment by kenOfYugen** [comment]
Ok, I see. Seems like the reasonable approach.
Closing this then!

**Comment by jjrv** [comment]
Version 0.3.5 with a fix for this issue is now released!
